version: '3'

services:

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
       - MYSQL_DATABASE=backend_demo
       - MYSQL_ROOT_USER=root
       - MYSQL_ROOT_PASSWORD=Ainch
    ports:
      - "3307:3306"

  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    ports:
     - "27017:27017"
    volumes:
      - db:/data/db

  app:
    container_name: diCD_api
    restart: unless-stopped
    build: .
    ports:
      - "51005:51005"
    depends_on:
      mysql:
        condition: service_started
      mongo:
        condition: service_started
 

volumes:
    db:
